# Generated by Django 5.0.6 on 2025-04-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emp_id", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=100)),
                ("date_of_joining", models.DateField()),
            ],
        ),
    ]
